name: Create Release

on:
  repository_dispatch:
    types: [release]

jobs:
  create-release:
    name: 'Create Release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'tags/${{ github.event.client_payload.version }}'

      - name: Extract Release Notes
        id: kacl
        uses: zogot/kacl-parser@0.0.4
        with:
          version: ${{ github.event.client_payload.version }}

      - name: GH Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body: ${{ steps.kacl.outputs.release }}

      - name: Publish Release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}